#Sources 
:sources: 
  Curso: 
    :poll_interval: 300
  Alumno: 
    :poll_interval: 300
 
:development: 
  :licensefile: settings/license.key
  :redis: localhost:6379
  :syncserver: http://localhost:9292/application/
:production: 
  :licensefile: settings/license.key
  :redis: localhost:6379
  :syncserver: http://localhost:9292/application/
:test: 
  :licensefile: settings/license.key
  :redis: localhost:6379
  :syncserver: http://localhost:9292/application/
